.TH "affichage.h" 3 "Sun Jun 14 2020" "Version V1.0" "IFB_projet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
affichage.h \- ficher header contenant les prototypes des fonctions relative à l'affichage  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBafficheMenuPrincipal\fP (int type)"
.br
.RI "affiche le logo du jeu puis le menu principal "
.ti -1c
.RI "int \fBafficheInterfacePli\fP (\fBCarte\fP dernierPli[], \fBCarte\fP \fBpli\fP[], char *pseudo[], \fBCarte\fP cartesEnMain[], \fBContrat\fP contratActuel, char message[], Joueur utilisteur, Joueur dernierVainqueur, int score[], int pointManche[], int type)"
.br
.RI "affiche l'interface de jeu durant un pli "
.ti -1c
.RI "void \fBmodifieTailleFenetre\fP (int nbLigneFenetre, int nbColloneFentre)"
.br
.RI "modifie la taille de la fenetre dans laquel le programme s'execute "
.ti -1c
.RI "void \fBafficheSousMenus\fP (char phrase[], char intitule[])"
.br
.RI "affiche les différents sous menus "
.ti -1c
.RI "void \fBafficheMain\fP (\fBCarte\fP carte[])"
.br
.RI "affiche les carte qu'un joueur a en main "
.ti -1c
.RI "void \fBafficheContrat\fP (\fBContrat\fP contrat, char *pseudo[], int version)"
.br
.RI "affiche un contrat "
.ti -1c
.RI "void \fBafficheMenuSelection\fP (char intitule[], char phrase[], int sautDeLigne)"
.br
.RI "affiche dans un cadre plusieurs chaines de carractères avec un certain nombre de lignes sautée entre chacunes d'elles "
.ti -1c
.RI "\fBContrat\fP \fBproposeContratUtilisateur\fP (\fBContrat\fP dernierContrat, Joueur parle, \fBCarte\fP *pCarteMain)"
.br
.RI "gère le choix du contrat par l'utilisateur "
.in -1c
.SH "Detailed Description"
.PP 
ficher header contenant les prototypes des fonctions relative à l'affichage 


.PP
\fBAuthor\fP
.RS 4
Carlo\&.A & Florian\&.C 
.RE
.PP
\fBVersion\fP
.RS 4
v1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
12 juin 2020 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void afficheContrat (\fBContrat\fP contrat, char * pseudo[], int version)"

.PP
affiche un contrat 
.PP
\fBParameters\fP
.RS 4
\fI\fBContrat\fP\fP contrat : contrat a afficher 
.br
\fIchar\fP *pseudo[]: tableau de pointeur contenant les pseudo des différents joueurs 
.br
\fIint\fP version : 1 pour la version belle et de grande taille et 2 pour la version courte 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "int afficheInterfacePli (\fBCarte\fP dernierPli[], \fBCarte\fP pli[], char * pseudo[], \fBCarte\fP cartesEnMain[], \fBContrat\fP contratActuel, char message[], Joueur utilisteur, Joueur dernierVainqueur, int score[], int pointManche[], int type)"

.PP
affiche l'interface de jeu durant un pli 
.PP
\fBParameters\fP
.RS 4
\fI\fBCarte\fP\fP dernierPli[] : tableau contenant les 4 cartes du dernier plis 
.br
\fI\fBCarte\fP\fP pli[] : tableau contenant les cartes du pli en cours, mettre 0, 0 si il n'y a pas de carte 
.br
\fIchar\fP *pseudo[] : tableau contenant les pseudo des 4 joueur 
.br
\fI\fBCarte\fP\fP cartesEnMain[] : tableau contenant les carte dans la main de l'utilisateur 
.br
\fI\fBContrat\fP\fP contratActuel : contrat qui est en cour dans cette manche 
.br
\fIchar\fP message[500] 
.br
\fIJoueur\fP utilisateur : donne la position de l'utilisateur, mettre SANS_Joueur pour faire une partie avec uniquement des ordinateur 
.br
\fIJoueur\fP dernierVainqueur : joueur aylant gagné le dernier pli 
.br
\fIint\fP score[] : tableau qui contient les score de la partie 
.br
\fIint\fP pointManche[] : tableau qui contient les points de la manche 
.br
\fIint\fP type : version de la fonction : 0 pour un affichage et une acquisition et 1 pour l'acquisition seulle 
.RE
.PP
\fBReturns\fP
.RS 4
int : valeur choisie par l'utilisateur 
.RE
.PP
< Formatage des chaine de caracère relative aux pseudo
.PP
< Formatage des chaine de caractère relative au message
.PP
< Formatage des chaine de caractère relative aux cartes
.PP
< Formatage des chaine de caractère relative au contrat
.SS "void afficheMain (\fBCarte\fP carte[])"

.PP
affiche les carte qu'un joueur a en main 
.PP
\fBParameters\fP
.RS 4
\fI\fBCarte\fP\fP carte[] : tableau contanant les carte 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "int afficheMenuPrincipal (int type)"

.PP
affiche le logo du jeu puis le menu principal 
.PP
\fBParameters\fP
.RS 4
\fItype\fP quel type de menu est souhaité 
.RE
.PP
\fBReturns\fP
.RS 4
la valeur de l'action que l'utilisateur decide de faire 
.RE
.PP

.SS "void afficheMenuSelection (char intitule[], char phrase[], int sautDeLigne)"

.PP
affiche dans un cadre plusieurs chaines de carractères avec un certain nombre de lignes sautée entre chacunes d'elles 
.PP
\fBParameters\fP
.RS 4
\fIchar\fP intitule []: titre du du cadre 
.br
\fIchar\fP phrase[] : les chaines de carractère séparés par des points virgules 
.br
\fIint\fP sautDeLigne : nombre de lignes à sauter entre chaque chaine de carractères 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
< contrôle le centrage du titre du sous-menu
.PP
< effacement de la chaine de carrateres
.PP
<efface l'écran et affiche le sous-menu avec le texte correspondant
.SS "void afficheSousMenus (char phrase[], char intitule[])"

.PP
affiche les différents sous menus 
.PP
\fBParameters\fP
.RS 4
\fIphrase\fP phrase correspondant au sous menu choisi 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP
< contrôle le centrage du titre du sous-menu
.PP
< découpe la phrase pour pouvoir l'afficher 
.br
.PP
<efface l'écran et affiche le sous-menu avec le texte correspondant
.SS "void modifieTailleFenetre (int nbLigneFenetre, int nbColloneFentre)"

.PP
modifie la taille de la fenetre dans laquel le programme s'execute 
.PP
\fBParameters\fP
.RS 4
\fInbLingeFenetre\fP : nombre de ligne de la fenetre 
.br
\fInbColloneFenetre\fP : nombre de collone de la fenetre 
.RE
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SS "\fBContrat\fP proposeContratUtilisateur (\fBContrat\fP dernierContrat, Joueur parle, \fBCarte\fP * pCarteMain)"

.PP
gère le choix du contrat par l'utilisateur 
.PP
\fBParameters\fP
.RS 4
\fI\fBContrat\fP\fP dernierContrat : dernier contrat proposé 
.br
\fIJoueur\fP parle : joueur qui parle 
.br
\fI\fBCarte\fP\fP *pCarteMain : pointeur sur le tableau qui stocke les carte dans la main du joueur 
.RE
.PP
\fBReturns\fP
.RS 4
\fBContrat\fP : nouveau contrat proposé par le joueur 
.RE
.PP
\fBParameters\fP
.RS 4
\fI\fP .RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IFB_projet from the source code\&.
