.TH "Carte" 3 "Sun Jun 14 2020" "Version V1.0" "IFB_projet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carte \- represente une carte d'un jeu de 32 cartes  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Couleur \fBcouleur\fP"
.br
.ti -1c
.RI "Valeur \fBvaleur\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
represente une carte d'un jeu de 32 cartes 
.SH "Field Documentation"
.PP 
.SS "Valeur valeur"
type Couleur, donne la famille à laquel la carte apprartient 

.SH "Author"
.PP 
Generated automatically by Doxygen for IFB_projet from the source code\&.
