.TH "Carte" 3 "Sat Jun 13 2020" "Version V1.0" "IFB_projet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carte
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Couleur \fBcouleur\fP"
.br
.ti -1c
.RI "Valeur \fBvaleur\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for IFB_projet from the source code\&.
