.TH "Contrat" 3 "Sun Jun 14 2020" "Version V1.0" "IFB_projet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Contrat \- represente un contrat à la belote coichée  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "Joueur \fBpreneur\fP"
.br
.ti -1c
.RI "NbPoint \fBnbPoint\fP"
.br
.ti -1c
.RI "Couleur \fBatout\fP"
.br
.ti -1c
.RI "Coinche \fBcoinche\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
represente un contrat à la belote coichée 

Permet d'avoir toutes les information concernant un contrat stocké dans une seuil et même variable 
.SH "Field Documentation"
.PP 
.SS "Couleur atout"
type NbPoint, nombre de point du contrat 
.SS "Coinche coinche"
type Couleur, couleur de l'atout qui à été prise pour le contrat 
.SS "NbPoint nbPoint"
type Joueur, joueur qui a pris le contrat 

.SH "Author"
.PP 
Generated automatically by Doxygen for IFB_projet from the source code\&.
