.TH "gestionFichier.h" 3 "Sun Jun 14 2020" "Version V1.0" "IFB_projet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gestionFichier.h \- ficher header contenant les prototypes des fonctions relative à la gestion des fichiers  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBecriturePseudo\fP (char *pPseudo, FILE *pFichier)"
.br
.RI "fonction qui recherche dans un fichier si le joueur est deja enregistré au le rajoute à la fin si ce n'est pas le cas "
.ti -1c
.RI "int \fBecrireStatistique\fP (FILE *fichier, int ligne, int statAModifier, int type)"
.br
.RI "modifie la valeur d'une statistique dans le fichier de sauvegarde des scores "
.ti -1c
.RI "int \fBecrireLeaderboard\fP (FILE *fichier, char *pseudo, int score)"
.br
.RI "vérifie si un nouveau record à été battu et l'ajoute si c'est le cas "
.in -1c
.SH "Detailed Description"
.PP 
ficher header contenant les prototypes des fonctions relative à la gestion des fichiers 


.PP
\fBAuthor\fP
.RS 4
Carlo\&.A & Florian\&.C 
.RE
.PP
\fBVersion\fP
.RS 4
v1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
12 juin 2020 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int ecrireLeaderboard (FILE * fichier, char * pseudo, int scoreJ)"

.PP
vérifie si un nouveau record à été battu et l'ajoute si c'est le cas 
.PP
\fBParameters\fP
.RS 4
\fIFILE\fP *fichier : pointeur vers fichier de meilleurs score 
.br
\fIchar\fP *pPseudo : pointeur vers le pseudo du joueur 
.br
\fIint\fP score : score a éventuellement enregistrer 
.RE
.PP
\fBReturns\fP
.RS 4
0 
.RE
.PP

.SS "int ecrireStatistique (FILE * fichier, int ligne, int statAModifier, int type)"

.PP
modifie la valeur d'une statistique dans le fichier de sauvegarde des scores 
.PP
\fBParameters\fP
.RS 4
\fIFILE\fP *fichier : pointeur vers le fichier 
.br
\fIint\fP ligne : ligne du fichier à laquelle sont sauvegardée les statistiques du joueur 
.br
\fIint\fP statAModifier : la nouvelle statistique à enregistrer 
.br
\fIint\fP type : vaut 1 pour mdifier le nombre de victoires, vaut 2 pour changer le score max, vaut 3 pour changer le nombre de manche min pour une victoire 
.RE
.PP
\fBReturns\fP
.RS 4
valeur enregistrée 
.RE
.PP

.SS "int ecriturePseudo (char * pPseudo, FILE * pFichier)"

.PP
fonction qui recherche dans un fichier si le joueur est deja enregistré au le rajoute à la fin si ce n'est pas le cas 
.PP
\fBParameters\fP
.RS 4
\fIchar\fP *pPseudo: pointeur vers le nom du joueur 
.br
\fIFILE\fP *pFichier : pointeur vers le fichier contenant les statistiques 
.RE
.PP
\fBReturns\fP
.RS 4
le numero de la ligne dans lequel est noté le pseudo 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for IFB_projet from the source code\&.
