.TH "main.c" 3 "Sun Jun 14 2020" "Version V1.0" "IFB_projet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- ficher contenant la fonction main  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "Entrée du programme\&. "
.in -1c
.SH "Detailed Description"
.PP 
ficher contenant la fonction main 


.PP
\fBAuthor\fP
.RS 4
Carlo\&.A & Florian\&.C 
.RE
.PP
\fBVersion\fP
.RS 4
v1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
12 juin 2020 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Entrée du programme\&. 
.PP
\fBAuthor\fP
.RS 4
Florian\&.C
.RE
.PP
\fBReturns\fP
.RS 4
EXIT_SUCCESS - Arrêt normal du programme 
.RE
.PP
< CODE FINAL
.PP
< definit la taille de la fennetre a 50 lignes et 91 colones
.PP
< FIN CODE FINAL
.SH "Author"
.PP 
Generated automatically by Doxygen for IFB_projet from the source code\&.
